"""
BackendAgent — stage 2 of the example pipeline.

Input : {"architecture": <output from ArchitectureAgent>}
Output: {
    "files": {"models.py": str, "repositories.py": str,
              "services.py": str, "routes.py": str},
    "entities_implemented": list[str],
    "route_count": int,
    "lines_of_code": int,
}

Generates real, importable Python code from the architecture plan.
Replace the template engine with LLM calls in v3 for richer output.
"""

from __future__ import annotations

from typing import Any

from src.agents.base import AgentTask, BaseAgent
from src.agents.registry import register


# ---------------------------------------------------------------------------
# Code template helpers
# ---------------------------------------------------------------------------

def _models_py(models: list[dict]) -> str:
    """Generate models.py — one @dataclass per model."""
    lines = [
        '"""Data models — generated by BackendAgent."""',
        "from __future__ import annotations",
        "from dataclasses import dataclass, field",
        "from datetime import datetime",
        "from typing import Optional",
        "import uuid",
        "",
    ]
    for model in models:
        name: str = model["name"]
        fields: list[str] = model["fields"]
        lines += [f"", f"@dataclass", f"class {name}:"]
        for field_decl in fields:
            field_name, _, field_type = field_decl.partition(": ")
            default = _default_for_type(field_name, field_type)
            lines.append(f"    {field_decl} = {default}")
        lines += [
            f"",
            f"    def __repr__(self) -> str:",
            f"        return f\"{name}(id={{self.id!r}})\"" if any("id:" in f for f in fields) else
            f"        return f\"{name}()\"",
        ]
    return "\n".join(lines) + "\n"


def _repositories_py(entities: list[str]) -> str:
    """Generate repositories.py — in-memory store with CRUD for each entity."""
    lines = [
        '"""Repositories — generated by BackendAgent."""',
        "from __future__ import annotations",
        "from typing import Any, Optional",
        "",
    ]
    for entity in entities:
        cls = f"{entity}Repository"
        entity_var = entity.lower()
        lines += [
            f"",
            f"class {cls}:",
            f'    """In-memory repository for {entity}. Replace with DB adapter in v3."""',
            f"",
            f"    def __init__(self) -> None:",
            f"        self._store: dict[str, Any] = {{}}",
            f"",
            f"    def find_by_id(self, id: str) -> Optional[Any]:",
            f"        return self._store.get(id)",
            f"",
            f"    def find_all(self) -> list[Any]:",
            f"        return list(self._store.values())",
            f"",
            f"    def save(self, {entity_var}: Any) -> Any:",
            f"        self._store[{entity_var}.id] = {entity_var}",
            f"        return {entity_var}",
            f"",
            f"    def delete(self, id: str) -> bool:",
            f"        if id in self._store:",
            f"            del self._store[id]",
            f"            return True",
            f"        return False",
        ]
    return "\n".join(lines) + "\n"


def _services_py(entities: list[str]) -> str:
    """Generate services.py — one service class per entity."""
    lines = [
        '"""Services — generated by BackendAgent."""',
        "from __future__ import annotations",
        "from typing import Any, Optional",
        "",
    ]
    for entity in entities:
        svc = f"{entity}Service"
        repo = f"{entity}Repository"
        entity_var = entity.lower()
        entity_var_pl = entity.lower() + "s"
        lines += [
            f"",
            f"class {svc}:",
            f'    """Business logic for {entity}."""',
            f"",
            f"    def __init__(self, repository: {repo}) -> None:",
            f"        self._repo = repository",
            f"",
            f"    def list_{entity_var_pl}(self) -> list[Any]:",
            f'        """Return all {entity_var_pl}."""',
            f"        return self._repo.find_all()",
            f"",
            f"    def get_{entity_var}(self, id: str) -> Optional[Any]:",
            f'        """Return a single {entity_var} by id, or None."""',
            f"        return self._repo.find_by_id(id)",
            f"",
            f"    def create_{entity_var}(self, data: dict) -> Any:",
            f'        """Validate data and persist a new {entity_var}."""',
            f"        # TODO: validate data fields against {entity}.__annotations__",
            f"        raise NotImplementedError",
            f"",
            f"    def update_{entity_var}(self, id: str, data: dict) -> Optional[Any]:",
            f'        """Apply partial update to an existing {entity_var}."""',
            f"        # TODO: fetch, merge fields, validate, save",
            f"        raise NotImplementedError",
            f"",
            f"    def delete_{entity_var}(self, id: str) -> bool:",
            f'        """Remove a {entity_var} permanently (Level-3 action)."""',
            f"        # TODO: check permissions before deletion",
            f"        return self._repo.delete(id)",
        ]
    return "\n".join(lines) + "\n"


def _routes_py(routes: list[dict], entities: list[str]) -> str:
    """Generate routes.py — one handler function per route."""
    lines = [
        '"""Route handlers — generated by BackendAgent."""',
        "from __future__ import annotations",
        "from typing import Any",
        "",
        "# Wire these handlers to your HTTP framework (FastAPI, Flask, etc.)",
        "# Each handler receives the relevant Service via dependency injection.",
        "",
    ]
    # Import all services
    for entity in entities:
        lines.append(f"# from services import {entity}Service")
    lines.append("")

    for route in routes:
        handler: str = route["handler"]
        method: str = route["method"]
        path: str = route["path"]
        level: int = route["security_level"]
        level_comment = {1: "Level 1 — Safe", 2: "Level 2 — Sensitive",
                         3: "Level 3 — Critical (human approval required)"}[level]

        has_id = "{id}" in path
        params = "id: str, " if has_id else ""

        lines += [
            f"",
            f"def {handler}({params}**kwargs: Any) -> Any:",
            f'    """',
            f"    {method} {path}",
            f"    Security: {level_comment}",
            f'    """',
            f"    # TODO: implement {handler}",
            f"    raise NotImplementedError",
        ]
    return "\n".join(lines) + "\n"


def _default_for_type(field_name: str, field_type: str) -> str:
    """Return a sensible default value expression for a given field type."""
    ft = field_type.strip()
    fn = field_name.strip()
    if fn == "id":
        return "field(default_factory=lambda: str(uuid.uuid4()))"
    if ft == "datetime":
        return "field(default_factory=datetime.utcnow)"
    if ft.startswith("Optional["):
        return "None"
    if ft.startswith("list["):
        return "field(default_factory=list)"
    if ft == "bool":
        return "False"
    if ft == "int":
        return "0"
    if ft == "float":
        return "0.0"
    if ft == "dict":
        return "field(default_factory=dict)"
    return '""'


# ---------------------------------------------------------------------------
# Agent
# ---------------------------------------------------------------------------

@register
class BackendAgent(BaseAgent):
    """
    Generates Python source files from an architecture plan.
    Stage 2 of 3 in the example pipeline.
    """

    name = "backend-agent"
    allowed_tools = ["read_file", "write_file"]

    def execute(self, task: AgentTask) -> dict[str, Any]:
        arch = task.input.get("architecture")
        if not arch:
            raise ValueError("Input 'architecture' is required.")

        entities: list[str] = arch.get("entities", [])
        models: list[dict] = arch.get("models", [])
        routes: list[dict] = arch.get("routes", [])

        if not entities:
            raise ValueError("Architecture plan contains no entities.")

        files = {
            "models.py":       _models_py(models),
            "repositories.py": _repositories_py(entities),
            "services.py":     _services_py(entities),
            "routes.py":       _routes_py(routes, entities),
        }

        loc = sum(code.count("\n") for code in files.values())

        return {
            "files": files,
            "entities_implemented": entities,
            "route_count": len(routes),
            "lines_of_code": loc,
        }
