"""
BackendAgent — stage 2 of the example pipeline.

Input : {"architecture": <output from ArchitectureAgent>}
Output: {
    "files": {
        "main.py":              FastAPI application entry point,
        "models.py":            Pydantic domain models,
        "schemas.py":           Create / Update / Response schemas,
        "services.py":          Business logic layer,
        "repositories.py":      In-memory data store,
        "routers/__init__.py":  Router aggregation,
        "routers/<entity>.py":  One APIRouter per entity,
        "requirements.txt":     Python dependencies,
        "README.md":            Setup and run instructions,
    },
    "entities_implemented": list[str],
    "route_count":          int,
    "lines_of_code":        int,   # Python files only
}

Generates a runnable FastAPI project from the architecture plan.
Replace template strings with LLM calls in v3 for richer, context-aware output.
"""

from __future__ import annotations

from typing import Any

from src.agents.base import AgentTask, BaseAgent
from src.agents.registry import register


# ---------------------------------------------------------------------------
# Field classification helpers
# ---------------------------------------------------------------------------

def _pydantic_default(field_name: str, field_type: str) -> str:
    """Return a Pydantic-compatible default expression for a field declaration."""
    fn = field_name.strip()
    ft = field_type.strip()

    if fn == "id":
        return 'Field(default_factory=lambda: str(uuid.uuid4()))'
    if ft == "datetime":
        return "Field(default_factory=datetime.utcnow)"
    if ft.startswith("Optional["):
        return "None"
    if ft.startswith("list["):
        return "Field(default_factory=list)"
    if ft == "dict":
        return "Field(default_factory=dict)"
    if ft == "bool":
        return "False"
    if ft == "int":
        return "0"
    if ft == "float":
        return "0.0"
    return '""'


def _is_auto_field(field_name: str) -> bool:
    """True for fields that should be excluded from Create/Update schemas."""
    fn = field_name.strip()
    return fn in ("id",) or fn.endswith("_at") or fn.endswith("_hash")


# ---------------------------------------------------------------------------
# File generators
# ---------------------------------------------------------------------------

def _models_py(models: list[dict]) -> str:
    """Pydantic BaseModel per entity."""
    lines = [
        '"""Domain models — generated by BackendAgent."""',
        "from __future__ import annotations",
        "",
        "from datetime import datetime",
        "from typing import Optional",
        "import uuid",
        "",
        "from pydantic import BaseModel, Field",
        "",
    ]
    for model in models:
        name: str = model["name"]
        fields: list[str] = model["fields"]
        lines += ["", f"class {name}(BaseModel):"]
        for field_decl in fields:
            fname, _, ftype = field_decl.partition(": ")
            default = _pydantic_default(fname, ftype)
            lines.append(f"    {field_decl} = {default}")
        lines += [
            "",
            "    class Config:",
            "        from_attributes = True",
        ]
    return "\n".join(lines) + "\n"


def _schemas_py(models: list[dict]) -> str:
    """Create / Update / Response schemas per entity."""
    lines = [
        '"""Request and response schemas — generated by BackendAgent."""',
        "from __future__ import annotations",
        "",
        "from datetime import datetime",
        "from typing import Optional",
        "",
        "from pydantic import BaseModel",
        "",
    ]
    for model in models:
        name: str = model["name"]
        all_fields: list[str] = model["fields"]

        # Writable fields: exclude auto-generated and secret fields
        writable = [f for f in all_fields if not _is_auto_field(f.split(":")[0])]
        # Response fields: exclude password-like fields
        response = [f for f in all_fields
                    if not f.split(":")[0].strip().endswith("_hash")]

        # --- Create schema ---
        lines += ["", f"class {name}Create(BaseModel):"]
        if writable:
            for field_decl in writable:
                lines.append(f"    {field_decl}")
        else:
            lines.append("    pass")

        # --- Update schema (all fields optional) ---
        lines += ["", f"class {name}Update(BaseModel):"]
        if writable:
            for field_decl in writable:
                fname, _, ftype = field_decl.partition(": ")
                if not ftype.startswith("Optional["):
                    lines.append(f"    {fname}: Optional[{ftype}] = None")
                else:
                    lines.append(f"    {field_decl} = None")
        else:
            lines.append("    pass")

        # --- Response schema ---
        lines += ["", f"class {name}Response(BaseModel):"]
        if response:
            for field_decl in response:
                lines.append(f"    {field_decl}")
        else:
            lines.append("    pass")
        lines += [
            "",
            "    class Config:",
            "        from_attributes = True",
        ]

    return "\n".join(lines) + "\n"


def _repositories_py(entities: list[str]) -> str:
    """In-memory CRUD repository per entity."""
    lines = [
        '"""Repositories — generated by BackendAgent."""',
        "from __future__ import annotations",
        "",
        "from typing import Any, Optional",
        "",
    ]
    for entity in entities:
        cls = f"{entity}Repository"
        ev = entity.lower()
        lines += [
            "",
            f"class {cls}:",
            f'    """In-memory store for {entity}. Replace with a DB adapter in v3."""',
            "",
            "    def __init__(self) -> None:",
            "        self._store: dict[str, Any] = {}",
            "",
            "    def find_by_id(self, id: str) -> Optional[Any]:",
            "        return self._store.get(id)",
            "",
            "    def find_all(self) -> list[Any]:",
            "        return list(self._store.values())",
            "",
            f"    def save(self, {ev}: Any) -> Any:",
            f"        self._store[{ev}.id] = {ev}",
            f"        return {ev}",
            "",
            "    def delete(self, id: str) -> bool:",
            "        if id in self._store:",
            "            del self._store[id]",
            "            return True",
            "        return False",
        ]
    return "\n".join(lines) + "\n"


def _services_py(entities: list[str]) -> str:
    """Service layer — one class per entity."""
    lines = [
        '"""Services — generated by BackendAgent."""',
        "from __future__ import annotations",
        "",
        "from typing import Optional",
        "",
    ]
    for entity in entities:
        svc = f"{entity}Service"
        repo_cls = f"{entity}Repository"
        ev = entity.lower()
        evpl = ev + "s"
        lines += [
            "",
            f"class {svc}:",
            f'    """Business logic for {entity}."""',
            "",
            f"    def __init__(self) -> None:",
            f"        from repositories import {repo_cls}",
            f"        self._repo = {repo_cls}()",
            "",
            f"    def list_{evpl}(self) -> list:",
            f'        """Return all {evpl}."""',
            f"        return self._repo.find_all()",
            "",
            f"    def get_{ev}(self, id: str) -> Optional[object]:",
            f'        """Return a single {ev} by id, or None."""',
            f"        return self._repo.find_by_id(id)",
            "",
            f"    def create_{ev}(self, data: dict) -> object:",
            f'        """Validate and persist a new {ev}."""',
            f"        # TODO: validate data, build {entity} model, save",
            f"        raise NotImplementedError",
            "",
            f"    def update_{ev}(self, id: str, data: dict) -> Optional[object]:",
            f'        """Apply a partial update to an existing {ev}."""',
            f"        # TODO: fetch existing, merge fields, validate, save",
            f"        raise NotImplementedError",
            "",
            f"    def delete_{ev}(self, id: str) -> bool:",
            f'        """Remove a {ev} permanently (Level-3 action)."""',
            f"        # TODO: check permissions before deletion",
            f"        return self._repo.delete(id)",
        ]
    return "\n".join(lines) + "\n"


def _router_py(entity: str) -> str:
    """FastAPI APIRouter for one entity."""
    ev = entity.lower()
    evpl = ev + "s"
    svc_cls = f"{entity}Service"
    lines = [
        f'"""Router for {entity} — generated by BackendAgent."""',
        "from __future__ import annotations",
        "",
        "from fastapi import APIRouter, HTTPException",
        "",
        f"from schemas import {entity}Create, {entity}Update, {entity}Response",
        f"from services import {svc_cls}",
        "",
        "router = APIRouter()",
        f"_service = {svc_cls}()",
        "",
        "",
        f'@router.get("/", response_model=list[{entity}Response])',
        f"def list_{evpl}() -> list:",
        f'    """List all {evpl}."""',
        f"    return _service.list_{evpl}()",
        "",
        "",
        f'@router.post("/", response_model={entity}Response, status_code=201)',
        f"def create_{ev}(data: {entity}Create) -> object:",
        f'    """Create a new {ev}."""',
        f"    try:",
        f"        return _service.create_{ev}(data.model_dump())",
        f"    except NotImplementedError:",
        f'        raise HTTPException(status_code=501, detail="Not yet implemented")',
        "",
        "",
        f'@router.get("/{{id}}", response_model={entity}Response)',
        f"def get_{ev}(id: str) -> object:",
        f'    """Get a single {ev} by id."""',
        f"    item = _service.get_{ev}(id)",
        f"    if item is None:",
        f'        raise HTTPException(status_code=404, detail="{entity} not found")',
        f"    return item",
        "",
        "",
        f'@router.put("/{{id}}", response_model={entity}Response)',
        f"def update_{ev}(id: str, data: {entity}Update) -> object:",
        f'    """Update an existing {ev}."""',
        f"    try:",
        f"        result = _service.update_{ev}(id, data.model_dump(exclude_unset=True))",
        f"    except NotImplementedError:",
        f'        raise HTTPException(status_code=501, detail="Not yet implemented")',
        f"    if result is None:",
        f'        raise HTTPException(status_code=404, detail="{entity} not found")',
        f"    return result",
        "",
        "",
        f'@router.delete("/{{id}}", status_code=204)',
        f"def delete_{ev}(id: str) -> None:",
        f'    """Delete a {ev}. Level-3 action — requires permission check."""',
        f"    if not _service.delete_{ev}(id):",
        f'        raise HTTPException(status_code=404, detail="{entity} not found")',
    ]
    return "\n".join(lines) + "\n"


def _routers_init_py(entities: list[str]) -> str:
    """routers/__init__.py — re-exports all entity routers."""
    lines = [
        '"""Router registry — generated by BackendAgent."""',
        "from __future__ import annotations",
        "",
    ]
    for entity in entities:
        ev = entity.lower()
        lines.append(f"from routers.{ev} import router as {ev}_router")
    lines += [
        "",
        "__all__ = [",
    ]
    for entity in entities:
        lines.append(f'    "{entity.lower()}_router",')
    lines.append("]")
    return "\n".join(lines) + "\n"


def _main_py(entities: list[str], project_name: str) -> str:
    """FastAPI application entry point."""
    lines = [
        f'"""FastAPI application — {project_name}"""',
        "from __future__ import annotations",
        "",
        "from fastapi import FastAPI",
        "",
    ]
    for entity in entities:
        ev = entity.lower()
        lines.append(f"from routers.{ev} import router as {ev}_router")
    lines += [
        "",
        f'app = FastAPI(title="{project_name}", version="0.1.0")',
        "",
        "",
        '@app.get("/health")',
        "def health() -> dict:",
        '    """Health check endpoint."""',
        '    return {"status": "ok"}',
        "",
    ]
    for entity in entities:
        ev = entity.lower()
        lines.append(
            f'app.include_router({ev}_router, prefix="/{ev}s", tags=["{ev}s"])'
        )
    return "\n".join(lines) + "\n"


def _requirements_txt(project_name: str) -> str:
    return (
        f"# {project_name} — Python dependencies\n"
        "fastapi>=0.111\n"
        "uvicorn[standard]>=0.29\n"
        "pydantic>=2.0\n"
    )


def _readme_md(project_name: str, entities: list[str]) -> str:
    entity_list = "\n".join(f"- `/{e.lower()}s`" for e in entities)
    return f"""\
# {project_name}

Generated by **AI Development System v2**.

## Setup

```bash
pip install -r requirements.txt
```

## Run

```bash
uvicorn main:app --reload
```

Open **http://localhost:8000/docs** for the interactive Swagger UI.

## Endpoints

{entity_list}

Each resource exposes:  `GET /` `POST /` `GET /{{id}}` `PUT /{{id}}` `DELETE /{{id}}`

## Next Steps

1. Implement `create_*` and `update_*` methods in `services.py`
2. Replace the in-memory repositories in `repositories.py` with a real DB adapter
3. Add authentication middleware to `main.py`
"""


# ---------------------------------------------------------------------------
# Agent
# ---------------------------------------------------------------------------

@register
class BackendAgent(BaseAgent):
    """
    Generates a runnable FastAPI project from an architecture plan.
    Stage 2 of 3 in the example pipeline.
    """

    name = "backend-agent"
    allowed_tools = ["read_file", "write_file"]

    def execute(self, task: AgentTask) -> dict[str, Any]:
        arch = task.input.get("architecture")
        if not arch:
            raise ValueError("Input 'architecture' is required.")

        entities: list[str] = arch.get("entities", [])
        models: list[dict]  = arch.get("models", [])
        routes: list[dict]  = arch.get("routes", [])

        if not entities:
            raise ValueError("Architecture plan contains no entities.")

        project_name: str = arch.get("feature", "Generated API")

        files: dict[str, str] = {
            "main.py":            _main_py(entities, project_name),
            "models.py":          _models_py(models),
            "schemas.py":         _schemas_py(models),
            "services.py":        _services_py(entities),
            "repositories.py":    _repositories_py(entities),
            "routers/__init__.py": _routers_init_py(entities),
        }
        for entity in entities:
            files[f"routers/{entity.lower()}.py"] = _router_py(entity)

        files["requirements.txt"] = _requirements_txt(project_name)
        files["README.md"]        = _readme_md(project_name, entities)

        py_files = {k: v for k, v in files.items() if k.endswith(".py")}
        loc = sum(code.count("\n") for code in py_files.values())

        return {
            "files":                files,
            "entities_implemented": entities,
            "route_count":          len(routes),
            "lines_of_code":        loc,
        }
